---
namespace: selfhosted
name: services
version: 1.3.1
readme: README.md
authors:
  - SpeakinTelnet <git@speakintel.net>

description: >
  A collection of ansible roles to deploy selfhosted services using Podman's Quadlet
license_file: LICENSE

tags:
  - infrastructure
  - homelab
  - selfhosted
  - quadlet

dependencies: {}
repository: https://github.com/ansible-selfhosted/selfhosted.services
issues: https://github.com/ansible-selfhosted/selfhosted.services/issues
