---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install hatch

      - name: ansible-lint
        run: hatch run lint:lint
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
